name: uno

services:
  # ----------------------------
  # AUTH DATABASE
  # ----------------------------
  auth-db:
    image: postgres:17-alpine
    container_name: auth_db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

  # ----------------------------
  # AUTH SERVICE
  # ----------------------------
  auth-app:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: auth_service_container
    restart: unless-stopped
    depends_on:
      - auth-db
    environment:
      DATABASE_URL: postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}?sslmode=disable
      JWT_SECRET: ${AUTH_JWT_SECRET}
      PORT: ${AUTH_SERVER_PORT:-8080}
    ports:
      - "${AUTH_SERVER_PORT:-8080}:${AUTH_SERVER_PORT:-8080}"
    networks:
      - auth-network
# ----------------------------
# NETWORK
# ----------------------------
networks:
  auth-network:
    driver: bridge

# ----------------------------
# VOLUMES
# ----------------------------
volumes:
  auth_postgres_data:
